import os
import json
import argparse
import shutil
from datetime import datetime

ENV_PATH = ".env"
BACKUP_FMT = ".env.bak.{ts}"

DEFAULT_KEYS = [
    "AWS_REGION",
    "S3_BUCKET",
    "RDS_HOST",
    "RDS_USER",
    "RDS_PASS",
    "RDS_DB",
    "COGNITO_POOL_ID",
    "COGNITO_CLIENT_ID",
    "FLASK_SECRET"
]

def backup_env(path=ENV_PATH):
    if os.path.exists(path):
        ts = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
        bak = BACKUP_FMT.format(ts=ts)
        shutil.copy2(path, bak)
        print(f"[ENV] Existing {path} backed up to {bak}")

def write_env_file(data, path=ENV_PATH):
    backup_env(path)
    lines = ["# Generated by setup_env.py - edit values as needed\n"]
    for k in DEFAULT_KEYS:
        v = data.get(k, "")
        # Avoid writing None
        lines.append(f"{k}={v}\n")
    with open(path, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print(f"[ENV] Wrote {os.path.abspath(path)}")

def load_config_files(aws_path="./config/aws_config.json", db_path="./config/db_config.json"):
    out = {}
    if os.path.exists(aws_path):
        try:
            with open(aws_path, "r", encoding="utf-8") as f:
                aws = json.load(f)
            out["AWS_REGION"] = aws.get("region", "")
            out["S3_BUCKET"] = aws.get("s3_bucket", "")
            out["COGNITO_POOL_ID"] = aws.get("user_pool_id", "")
            out["COGNITO_CLIENT_ID"] = aws.get("user_pool_client_id", "")
            print(f"[ENV] Loaded AWS config from {os.path.abspath(aws_path)}")
        except Exception as e:
            print(f"[ENV] Failed to read {aws_path}: {e}")
    if os.path.exists(db_path):
        try:
            with open(db_path, "r", encoding="utf-8") as f:
                db = json.load(f)
            out["RDS_HOST"] = db.get("db_host", "")
            out["RDS_USER"] = db.get("db_user", "")
            out["RDS_PASS"] = db.get("db_password", "")
            out["RDS_DB"] = db.get("db_name", "")
            print(f"[ENV] Loaded DB config from {os.path.abspath(db_path)}")
        except Exception as e:
            print(f"[ENV] Failed to read {db_path}: {e}")
    return out

def sample_env():
    return {
        "AWS_REGION": "us-east-1",
        "S3_BUCKET": "bucket-name",
        "RDS_HOST": "example.us-east-1.rds.amazonaws.com",
        "RDS_USER": "admin",
        "RDS_PASS": "CloudGallery123!",
        "RDS_DB": "cloudgallery",
        "COGNITO_POOL_ID": "us-east-1_XXXX",
        "COGNITO_CLIENT_ID": "XXXX",
        "FLASK_SECRET": ""
    }

def interactive_fill(base):
    print("[ENV] Interactive mode: press Enter to keep shown default value.")
    for k in DEFAULT_KEYS:
        cur = base.get(k, "")
        prompt = f"{k} [{cur}]: "
        try:
            val = input(prompt).strip()
        except KeyboardInterrupt:
            print("\n[ENV] Aborted by user.")
            raise SystemExit(1)
        if val:
            base[k] = val
    return base

def parse_args():
    p = argparse.ArgumentParser(description="Generate .env for CloudGallery")
    grp = p.add_mutually_exclusive_group()
    grp.add_argument("--from-config", action="store_true", help="Populate .env from ./config/*.json (if present)")
    grp.add_argument("--sample", action="store_true", help="Write sample .env (default when no flags)")
    grp.add_argument("--interactive", action="store_true", help="Prompt for each env value")
    p.add_argument("--force", action="store_true", help="Overwrite .env without extra backup (still creates timestamped backup)")
    return p.parse_args()

def main():
    args = parse_args()
    if args.from_config:
        data = load_config_files()
        # fill any missing with empty strings
        for k in DEFAULT_KEYS:
            data.setdefault(k, "")
    elif args.interactive:
        data = sample_env()
        data = interactive_fill(data)
    else:
        # default to sample
        data = sample_env()

    write_env_file(data)

if __name__ == "__main__":
    main()